### ISSUE TITLE
Bug Report: Secondary Weapons not being displayed

### ISSUE THREAD

**Issue by PiZZAD0X** [unitedoperations/uo_briefingkit#4]
#### Description of issue

Units without secondary weapons display an unknown icon (placeholder icon for when item picture value is nil)

#### Steps to reproduce

1.  Create a mission with two units, one with a secondary weapon and one without.
2.  Load mission 

#### Expected behaviour

Secondary weapon placeholder unknown should be either blank or backpack

#### Screenshots

![20190111174744_1](https://user-images.githubusercontent.com/11909749/51067455-53326e80-15c7-11e9-81be-a5afe6969d5f.jpg)

#### Additional context

nil.

**Comment by PiZZAD0X** [comment]
If this inline function is given a nil secondary weapon param, it still results in an unknown/placeholder icon displayed. https://github.com/unitedoperations/uo_briefingkit/blob/188e6b4af70461efede601e3e51c19fc3b999b14/xeh_postinit.sqf#L23

possible nil call to `_getpicture`
https://github.com/unitedoperations/uo_briefingkit/blob/188e6b4af70461efede601e3e51c19fc3b999b14/xeh_postinit.sqf#L218

**Comment by callensm** [comment]
#5 has been merged. Close the issue once confirmed resolved.
